name: Weekly Tech Report

on:
  schedule:
    - cron: '0 14 * * 1'  # 每周一北京时间14:00运行
  workflow_dispatch:
# on: [push]

jobs:
  generate-report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的token
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: pull latest code
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git pull origin main --rebase

    - name: Run data collector
      run: python scripts/collector.py
      
    - name: Process data
      run: python scripts/processor.py
      
    - name: Generate report
      run: python scripts/reporter.py
      
    - name: Commit and push report
      run: |
        git add tech_trends_report.md
        git commit -m "Auto-update weekly tech report"
        git push

    - name: Validate email recipient
      run: |
        if [ -z "${{ secrets.REPORT_RECEIVER }}" ]; then
          echo "ERROR: REPORT_RECEIVER secret is not set!"
          exit 1
        else
          echo "Sending report to ${{ secrets.REPORT_RECEIVER }}"
        fi

    - name: Create GitHub Issue
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs').promises;
          const report = await fs.readFile('tech_trends_report.md', 'utf8');
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `技术热点周报 - ${new Date().toISOString().split('T')[0]}`,
            body: `## 自动生成的技术热点报告\n\n${report}`
          });