name: Weekly Tech Report

on:
  schedule:
    - cron: '0 14 * * 1'  # 每周一北京时间14:00运行
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的token
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data collector
      run: python scripts/collector.py
      
    - name: Process data
      run: python scripts/processor.py
      
    - name: Generate report
      run: python scripts/reporter.py
      
    - name: Commit and push report
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add tech_trends_report.md
        git commit -m "Auto-update weekly tech report"
        git push
        
    - name: Send email via GitHub App
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: actions@github.com  # GitHub提供的专用邮箱
        password: ${{ secrets.GITHUB_TOKEN }}  # 使用GITHUB_TOKEN作为"密码"
        subject: "技术热点周报 - $(date +'%Y-%m-%d')"
        body: file://tech_trends_report.md
        to: ${{ secrets.REPORT_RECEIVER }}
        from: GitHub Actions